export const STORE = {
  name: "Pet Store",
  nameAr: "بت ستور",
  slogan: '"Your Dependable partner in PetHood"',
  sloganAr: '"شريكك الموثوق في عالم الحيوانات الأليفة"',
  currency: "KD",
  currencyISO: "KWD",
  currencyDecimals: 3,
  country: "Kuwait",
  countryCode: "+965",
  baseLat: 29.3117,
  baseLng: 47.4818,
  domain: "www.petstorekuwait.com",
  slug: "pet-store",
  logo: "https://tapcom-live.ams3.cdn.digitaloceanspaces.com/media/cache/20/cd/20cdb0fccdeb8e77bda91a31a8c3c078.jpg",
  logoAr: "https://tapcom-live.ams3.cdn.digitaloceanspaces.com/media/cache/3c/5a/3c5ab9f8bf73c4aa958bd48aefbeb08e.jpg",
  cover: "https://tapcom-live.ams3.cdn.digitaloceanspaces.com/media/pet-store/covers/IMG_5580.jpeg",
  whatsapp: "96598805010",
  phone: "98805010",
  callCenter: "22207053",
  instagram: "https://www.instagram.com/petstore.kw",
  email: "petstorekw@gmail.com",
} as const;

export const BRANCHES = [
  { id: 1, name: "Pet Store - Al Rai", nameAr: "بت ستور - العلي" },
  { id: 2, name: "Pet Store - Salmiya", nameAr: "بت ستور - السالمية" },
] as const;

export const CATEGORIES = [
  { slug: "special-offer", name: "Special Offer", nameAr: "عرض خاص" },
  { slug: "cat-wet-food", name: "Cat Wet Food", nameAr: "طعام رطب للقطط" },
  { slug: "dog-wet-food", name: "Dog Wet Food", nameAr: "طعام رطب للكلاب" },
  { slug: "cat-dry-food", name: "Cat Dry Food", nameAr: "الطعام الجاف للقطط" },
  { slug: "dog-dry-food", name: "Dog Dry Food", nameAr: "الطعام الجاف للكلاب" },
  { slug: "cat-treats", name: "Cat Treats", nameAr: "مكافأت القطط" },
  { slug: "dog-treats", name: "Dog Treats", nameAr: "وجبات مكافأة للكلاب" },
  { slug: "pet-carriers", name: "Pets Carrier & Travel Bags", nameAr: "شنط واقفاص الحيوانات الأليفة" },
  { slug: "cat-litter", name: "Cat Litter and Boxes", nameAr: "تراب وصناديق للقطط" },
  { slug: "pet-beds", name: "Pet Beds & Houses", nameAr: "منزل وسرائر الحيوانات الأليفة" },
  { slug: "cat-accessories", name: "Cat Accessories", nameAr: "اكسسوارات القطط" },
  { slug: "dog-accessories", name: "Dog Accessories", nameAr: "اكسسوارات الكلاب" },
  { slug: "healthcare", name: "Healthcare & Supplements", nameAr: "الرعاية الصحية والمكملات الغذائية" },
  { slug: "grooming", name: "Grooming & Hygiene", nameAr: "الحلاقة والنظافة" },
  { slug: "cat-scratchers", name: "Cat Scratchers", nameAr: "خداشات القطط" },
  { slug: "pet-cage", name: "Pet Cage", nameAr: "أقفاص الحيوانات الأليفة" },
  { slug: "cat-toys", name: "Cat Toys", nameAr: "ألعاب القطط" },
  { slug: "pet-milk", name: "Pet Milk", nameAr: "حليب القطط" },
  { slug: "dog-toys", name: "Dog Toys", nameAr: "ألعاب الكلاب" },
  { slug: "bird-food", name: "Bird Food", nameAr: "طعام الطيور" },
  { slug: "bird-toys", name: "Bird Toys", nameAr: "ألعاب الطيور" },
  { slug: "bird-cage", name: "Bird Cage", nameAr: "قفص الطيور والحامل" },
  { slug: "bird-accessories", name: "Bird Needs & Accessories", nameAr: "اكسسوارات واحتياجات الطيور" },
  { slug: "rabbit-food", name: "Rabbit Food", nameAr: "غذاء الأرانب" },
  { slug: "rabbit-accessories", name: "Rabbit Needs & Accessories", nameAr: "احتياجات واكسسوارات الأرانب" },
  { slug: "fish-food", name: "Fish Food", nameAr: "طعام الأسماك" },
  { slug: "fish-accessories", name: "Fish Needs & Accessories", nameAr: "احتياجات واكسسوارات الأسماك" },
  { slug: "hamster-accessories", name: "Hamster Needs & Accessories", nameAr: "احتياجات واكسسوارات الهامستر" },
  { slug: "hamster-food", name: "Hamster Food", nameAr: "طعام الهامستر" },
  { slug: "reptile-food", name: "Reptile Food", nameAr: "طعام الزواحف" },
  { slug: "reptile-accessories", name: "Reptile Needs & Accessories", nameAr: "احتياجات واكسسوارات الزواحف" },
] as const;

export const UI_STRINGS = {
  delivery: "Delivery",
  deliveryAr: "توصيل",
  pickup: "Pickup",
  pickupAr: "استلام",
  deliverTo: "Deliver to",
  deliverToAr: "توصيل الى",
  chooseLocation: "Choose location",
  chooseLocationAr: "اختر منطقة",
  edit: "Edit",
  editAr: "تغيير",
  earliestArrival: "Earliest arrival",
  earliestArrivalAr: "أقرب وصول",
  filterSort: "Filter & Sort",
  filterSortAr: "التصفية و الترتيب",
  addToCart: "Add to Cart",
  addToCartAr: "اضف للسلة",
  buyNow: "Buy now",
  buyNowAr: "اشتر الان",
  selectLocation: "Select your location",
  selectLocationAr: "اختر منطقتك",
  search: "Search for a product",
  searchAr: "ابحث عن منتج",
  description: "Description",
  descriptionAr: "الوصف",
  specialRequests: "Special Requests",
  specialRequestsAr: "ملاحظات",
  shareWithFriend: "SHARE WITH A FRIEND",
  shareWithFriendAr: "شارك مع صديق",
  ourBranches: "Our branches",
  ourBranchesAr: "فروعنا",
  connectWithUs: "Connect with us",
  connectWithUsAr: "تواصل معنا",
  reviewOrder: "Review Order",
  reviewOrderAr: "مراجعة الطلب",
  placeOrder: "Place Order",
  placeOrderAr: "اتمام الطلب",
  menu: "Menu",
  menuAr: "القائمة",
  outOfStock: "Out of stock",
  outOfStockAr: "غير متوفر",
  addToCartButton: "Add",
  addToCartButtonAr: "اضف",
} as const;
